# Generated by Django 3.1.7 on 2021-12-13 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cryptodata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='Crypto Data', max_length=500)),
                ('date', models.CharField(default='Crypto Data', max_length=500)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ZoomSwap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='Crypto Data', max_length=500)),
                ('date', models.CharField(default='Crypto Data', max_length=500)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='CryptoData',
            new_name='GameFantasyToken',
        ),
    ]
