# Generated by Django 3.1.7 on 2021-12-17 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211213_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('company_name', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=100)),
                ('proof_of_payment', models.CharField(max_length=100)),
                ('about_project', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unvetted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.CharField(max_length=120)),
                ('telegram_url', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='media')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='GameFantasyToken',
        ),
        migrations.DeleteModel(
            name='Vitality',
        ),
        migrations.DeleteModel(
            name='ZoomSwap',
        ),
    ]
