# Generated by Django 3.1.7 on 2021-12-26 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_iotexchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotexChartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.CharField(default='', max_length=200)),
                ('market_cap', models.CharField(default='', max_length=200)),
                ('addresses', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='iotexchart',
            name='price',
            field=models.CharField(default='', max_length=200),
        ),
    ]
